version: "3"

services:
  client:
    restart: always
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
    - ./client/:/usr/src/app/
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY
      - DB_ENGINE
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - REDIS_HOST
      - REDIS_PORT
    volumes:
    - ./backend/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python3 manage.py runworker channel_layer
    environment:
      - SECRET_KEY
      - DB_ENGINE
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - POSTGRES_PORT
      - REDIS_HOST
      - REDIS_PORT
    volumes:
      - ./backend/:/app/
    links:
      - redis
    depends_on:
      - redis
  postgres:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postresql/data
  redis:
    restart: always
    image: redis:latest
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  client:
  backend:
  worker:
  pgdata:
  redisdata: