import { useState, useEffect } from "react";
import { useSelector, useDispatch } from "react-redux";
import { resetRegistered, login } from "../features/authSlice";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

const Login = () => {
  const dispatch = useDispatch();
  const router = useRouter();
  const { isAuthenticated } = useSelector((state) => state.auth);

  const [formData, setFormData] = useState({
    email: "",
    password: "",
  });

  const { email, password } = formData;

  const onChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const onSubmit = (e) => {
    e.preventDefault();

    dispatch(login(formData));
  };

  useEffect(() => {
    if (dispatch && dispatch !== null && dispatch !== undefined)
      dispatch(resetRegistered());
  }, [dispatch]);

  useEffect(() => {
    if (isAuthenticated) {
      router.push("/");
    }
  }, [isAuthenticated]);

  return (
    <>
      <Head>
        <title>Login - Wazzapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </Head>
      <main className="flex items-center justify-center bg-primary">
        <div className="w-3/5 h-2/3 bg-secondary rounded">
          <form
            onSubmit={onSubmit}
            className="flex flex-col items-center justify-center h-full gap-5"
          >
            <input
              type="email"
              placeholder="email"
              className="w-fit p-3"
              name="email"
              value={email}
              onChange={onChange}
            />
            <input
              type="password"
              placeholder="password"
              className="w-fit p-3"
              name="password"
              value={password}
              onChange={onChange}
            />
            <button type="submit" className="text-stone-100">
              Log In
            </button>
          </form>
          <Link href="/register">
            <a className="text-stone-400">Register</a>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Login;
