import { useContext } from "react";
import AuthContext from "../context/AuthContext";
import Head from "next/head";
import Link from "next/link";

const Login = () => {
  const { registerUser } = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Register - Wazzapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon/favicon.ico" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/favicon/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon/favicon-16x16.png"
        />
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </Head>
      <main className="flex items-center justify-center bg-primary">
        <div className="w-3/5 h-2/3 bg-secondary rounded">
          <form
            onSubmit={registerUser}
            className="flex flex-col items-center justify-center h-full gap-5"
          >
            <input
              type="email"
              name="email"
              placeholder="email"
              className="w-fit p-3"
            />
            <input
              type="password"
              name="password"
              placeholder="password"
              className="w-fit p-3"
            />
            <input
              type="text"
              name="firstName"
              placeholder="First name"
              className="w-fit p-3"
            />
            <input
              type="text"
              name="lastName"
              placeholder="Last name"
              className="w-fit p-3"
            />
            <button type="submit" className="text-stone-100">
              Register
            </button>
          </form>
          <Link href="/login">
            <a>Login</a>
          </Link>
        </div>
      </main>
    </>
  );
};

export default Login;
